[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://REPLACE_WITH_BACKEND_URL/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/simulate_match/*"
  to = "https://REPLACE_WITH_BACKEND_URL/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/play_match/*"
  to = "https://REPLACE_WITH_BACKEND_URL/:splat"
  status = 200
  force = true
